/*
* generated by Xtext
*/
package co.edu.uniandes.mono.gesco.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("co/edu/uniandes/mono/gesco/parser/antlr/internal/InternalDSL.tokens");
	}
}
