/*
* generated by Xtext
*/
package co.edu.uniandes.mono.gesco.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ConfiguracionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Configuracion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfiguracionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConfiguracionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cSistemaOperativoAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cSistemaOperativoSistemaOperativoParserRuleCall_3_0_0 = (RuleCall)cSistemaOperativoAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cSistemaOperativoAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cSistemaOperativoSistemaOperativoParserRuleCall_3_1_1_0 = (RuleCall)cSistemaOperativoAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Configuracion:
		//	{Configuracion} "Configuracion" "{" (sistemaOperativo+=SistemaOperativo ("," sistemaOperativo+=SistemaOperativo)*)?
		//	"}";
		public ParserRule getRule() { return rule; }

		//{Configuracion} "Configuracion" "{" (sistemaOperativo+=SistemaOperativo ("," sistemaOperativo+=SistemaOperativo)*)? "}"
		public Group getGroup() { return cGroup; }

		//{Configuracion}
		public Action getConfiguracionAction_0() { return cConfiguracionAction_0; }

		//"Configuracion"
		public Keyword getConfiguracionKeyword_1() { return cConfiguracionKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(sistemaOperativo+=SistemaOperativo ("," sistemaOperativo+=SistemaOperativo)*)?
		public Group getGroup_3() { return cGroup_3; }

		//sistemaOperativo+=SistemaOperativo
		public Assignment getSistemaOperativoAssignment_3_0() { return cSistemaOperativoAssignment_3_0; }

		//SistemaOperativo
		public RuleCall getSistemaOperativoSistemaOperativoParserRuleCall_3_0_0() { return cSistemaOperativoSistemaOperativoParserRuleCall_3_0_0; }

		//("," sistemaOperativo+=SistemaOperativo)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//sistemaOperativo+=SistemaOperativo
		public Assignment getSistemaOperativoAssignment_3_1_1() { return cSistemaOperativoAssignment_3_1_1; }

		//SistemaOperativo
		public RuleCall getSistemaOperativoSistemaOperativoParserRuleCall_3_1_1_0() { return cSistemaOperativoSistemaOperativoParserRuleCall_3_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class SistemaOperativoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SistemaOperativo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSistemaOperativoAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVersionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVersionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVersionEStringParserRuleCall_4_0 = (RuleCall)cVersionAssignment_4.eContents().get(0);
		private final Keyword cDescripcionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDescripcionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDescripcionEStringParserRuleCall_6_0 = (RuleCall)cDescripcionAssignment_6.eContents().get(0);
		private final Keyword cArquitecturaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cArquitecturaAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cArquitecturaArquitecturaEnumRuleCall_8_0 = (RuleCall)cArquitecturaAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cFuentesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cFuentesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cFuentesFuentesParserRuleCall_9_2_0 = (RuleCall)cFuentesAssignment_9_2.eContents().get(0);
		private final Assignment cFuentesAssignment_9_3 = (Assignment)cGroup_9.eContents().get(3);
		private final RuleCall cFuentesFuentesParserRuleCall_9_3_0 = (RuleCall)cFuentesAssignment_9_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRequerimientosKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cRequerimientosAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cRequerimientosSoftwareParserRuleCall_12_0 = (RuleCall)cRequerimientosAssignment_12.eContents().get(0);
		private final Assignment cRequerimientosAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cRequerimientosSoftwareParserRuleCall_13_0 = (RuleCall)cRequerimientosAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//SistemaOperativo:
		//	{SistemaOperativo} name=EString "{" "version" version=EString "descripcion" descripcion=EString "arquitectura"
		//	arquitectura=Arquitectura ("fuentes" "{" fuentes+=Fuentes fuentes+=Fuentes* "}")? "requerimientos" "{"
		//	requerimientos+=Software requerimientos+=Software* "}" "}";
		public ParserRule getRule() { return rule; }

		//{SistemaOperativo} name=EString "{" "version" version=EString "descripcion" descripcion=EString "arquitectura"
		//arquitectura=Arquitectura ("fuentes" "{" fuentes+=Fuentes fuentes+=Fuentes* "}")? "requerimientos" "{"
		//requerimientos+=Software requerimientos+=Software* "}" "}"
		public Group getGroup() { return cGroup; }

		//{SistemaOperativo}
		public Action getSistemaOperativoAction_0() { return cSistemaOperativoAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"version"
		public Keyword getVersionKeyword_3() { return cVersionKeyword_3; }

		//version=EString
		public Assignment getVersionAssignment_4() { return cVersionAssignment_4; }

		//EString
		public RuleCall getVersionEStringParserRuleCall_4_0() { return cVersionEStringParserRuleCall_4_0; }

		//"descripcion"
		public Keyword getDescripcionKeyword_5() { return cDescripcionKeyword_5; }

		//descripcion=EString
		public Assignment getDescripcionAssignment_6() { return cDescripcionAssignment_6; }

		//EString
		public RuleCall getDescripcionEStringParserRuleCall_6_0() { return cDescripcionEStringParserRuleCall_6_0; }

		//"arquitectura"
		public Keyword getArquitecturaKeyword_7() { return cArquitecturaKeyword_7; }

		//arquitectura=Arquitectura
		public Assignment getArquitecturaAssignment_8() { return cArquitecturaAssignment_8; }

		//Arquitectura
		public RuleCall getArquitecturaArquitecturaEnumRuleCall_8_0() { return cArquitecturaArquitecturaEnumRuleCall_8_0; }

		//("fuentes" "{" fuentes+=Fuentes fuentes+=Fuentes* "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"fuentes"
		public Keyword getFuentesKeyword_9_0() { return cFuentesKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//fuentes+=Fuentes
		public Assignment getFuentesAssignment_9_2() { return cFuentesAssignment_9_2; }

		//Fuentes
		public RuleCall getFuentesFuentesParserRuleCall_9_2_0() { return cFuentesFuentesParserRuleCall_9_2_0; }

		//fuentes+=Fuentes*
		public Assignment getFuentesAssignment_9_3() { return cFuentesAssignment_9_3; }

		//Fuentes
		public RuleCall getFuentesFuentesParserRuleCall_9_3_0() { return cFuentesFuentesParserRuleCall_9_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }

		//"requerimientos"
		public Keyword getRequerimientosKeyword_10() { return cRequerimientosKeyword_10; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }

		//requerimientos+=Software
		public Assignment getRequerimientosAssignment_12() { return cRequerimientosAssignment_12; }

		//Software
		public RuleCall getRequerimientosSoftwareParserRuleCall_12_0() { return cRequerimientosSoftwareParserRuleCall_12_0; }

		//requerimientos+=Software*
		public Assignment getRequerimientosAssignment_13() { return cRequerimientosAssignment_13; }

		//Software
		public RuleCall getRequerimientosSoftwareParserRuleCall_13_0() { return cRequerimientosSoftwareParserRuleCall_13_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class FuentesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Fuentes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFuentesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFuenteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cAutorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAutorAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAutorEStringParserRuleCall_6_0 = (RuleCall)cAutorAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cFuenteKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFuenteAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFuenteEStringParserRuleCall_9_0 = (RuleCall)cFuenteAssignment_9.eContents().get(0);
		private final Keyword cCommaKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cTipoFuenteKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cTipoFuenteAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cTipoFuenteEStringParserRuleCall_12_0 = (RuleCall)cTipoFuenteAssignment_12.eContents().get(0);
		private final Keyword cSemicolonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Fuentes:
		//	{Fuentes} "Fuente" "=" name=EString "," "autor:" autor=EString "," "fuente:" fuente=EString "," "tipoFuente:"
		//	tipoFuente=EString ";";
		public ParserRule getRule() { return rule; }

		//{Fuentes} "Fuente" "=" name=EString "," "autor:" autor=EString "," "fuente:" fuente=EString "," "tipoFuente:"
		//tipoFuente=EString ";"
		public Group getGroup() { return cGroup; }

		//{Fuentes}
		public Action getFuentesAction_0() { return cFuentesAction_0; }

		//"Fuente"
		public Keyword getFuenteKeyword_1() { return cFuenteKeyword_1; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }

		//"autor:"
		public Keyword getAutorKeyword_5() { return cAutorKeyword_5; }

		//autor=EString
		public Assignment getAutorAssignment_6() { return cAutorAssignment_6; }

		//EString
		public RuleCall getAutorEStringParserRuleCall_6_0() { return cAutorEStringParserRuleCall_6_0; }

		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }

		//"fuente:"
		public Keyword getFuenteKeyword_8() { return cFuenteKeyword_8; }

		//fuente=EString
		public Assignment getFuenteAssignment_9() { return cFuenteAssignment_9; }

		//EString
		public RuleCall getFuenteEStringParserRuleCall_9_0() { return cFuenteEStringParserRuleCall_9_0; }

		//","
		public Keyword getCommaKeyword_10() { return cCommaKeyword_10; }

		//"tipoFuente:"
		public Keyword getTipoFuenteKeyword_11() { return cTipoFuenteKeyword_11; }

		//tipoFuente=EString
		public Assignment getTipoFuenteAssignment_12() { return cTipoFuenteAssignment_12; }

		//EString
		public RuleCall getTipoFuenteEStringParserRuleCall_12_0() { return cTipoFuenteEStringParserRuleCall_12_0; }

		//";"
		public Keyword getSemicolonKeyword_13() { return cSemicolonKeyword_13; }
	}

	public class SoftwareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Software");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSoftwareAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSoftwareKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cVersionKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVersionAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVersionEStringParserRuleCall_4_2_0 = (RuleCall)cVersionAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cDescripcionKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDescripcionAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cDescripcionEStringParserRuleCall_5_2_0 = (RuleCall)cDescripcionAssignment_5_2.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cArquitecturaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cArquitecturaAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cArquitecturaArquitecturaEnumRuleCall_8_0 = (RuleCall)cArquitecturaAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cRutaDestinoKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cRutaDestinoAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cRutaDestinoEStringParserRuleCall_9_2_0 = (RuleCall)cRutaDestinoAssignment_9_2.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cDependenciaKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Assignment cDependenciaAssignment_10_3 = (Assignment)cGroup_10.eContents().get(3);
		private final CrossReference cDependenciaSoftwareCrossReference_10_3_0 = (CrossReference)cDependenciaAssignment_10_3.eContents().get(0);
		private final RuleCall cDependenciaSoftwareEStringParserRuleCall_10_3_0_1 = (RuleCall)cDependenciaSoftwareCrossReference_10_3_0.eContents().get(1);
		private final Group cGroup_10_4 = (Group)cGroup_10.eContents().get(4);
		private final Keyword cCommaKeyword_10_4_0 = (Keyword)cGroup_10_4.eContents().get(0);
		private final Assignment cDependenciaAssignment_10_4_1 = (Assignment)cGroup_10_4.eContents().get(1);
		private final CrossReference cDependenciaSoftwareCrossReference_10_4_1_0 = (CrossReference)cDependenciaAssignment_10_4_1.eContents().get(0);
		private final RuleCall cDependenciaSoftwareEStringParserRuleCall_10_4_1_0_1 = (RuleCall)cDependenciaSoftwareCrossReference_10_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10_5 = (Keyword)cGroup_10.eContents().get(5);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cOrigenKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_11_2 = (Keyword)cGroup_11.eContents().get(2);
		private final Assignment cOrigenAssignment_11_3 = (Assignment)cGroup_11.eContents().get(3);
		private final CrossReference cOrigenFuentesCrossReference_11_3_0 = (CrossReference)cOrigenAssignment_11_3.eContents().get(0);
		private final RuleCall cOrigenFuentesEStringParserRuleCall_11_3_0_1 = (RuleCall)cOrigenFuentesCrossReference_11_3_0.eContents().get(1);
		private final Group cGroup_11_4 = (Group)cGroup_11.eContents().get(4);
		private final Keyword cCommaKeyword_11_4_0 = (Keyword)cGroup_11_4.eContents().get(0);
		private final Assignment cOrigenAssignment_11_4_1 = (Assignment)cGroup_11_4.eContents().get(1);
		private final CrossReference cOrigenFuentesCrossReference_11_4_1_0 = (CrossReference)cOrigenAssignment_11_4_1.eContents().get(0);
		private final RuleCall cOrigenFuentesEStringParserRuleCall_11_4_1_0_1 = (RuleCall)cOrigenFuentesCrossReference_11_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_5 = (Keyword)cGroup_11.eContents().get(5);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Software:
		//	{Software} "Software" "=" name=EString ("," "version:" version=EString)? ("," "descripcion:" descripcion=EString)?
		//	"," "arquitectura:" arquitectura=Arquitectura ("," "rutaDestino:" rutaDestino=EString)? ("," "dependencia:" "("
		//	dependencia+=[Software|EString] ("," dependencia+=[Software|EString])* ")")? ("," "origen:" "("
		//	origen+=[Fuentes|EString] ("," origen+=[Fuentes|EString])* ")")? ";";
		public ParserRule getRule() { return rule; }

		//{Software} "Software" "=" name=EString ("," "version:" version=EString)? ("," "descripcion:" descripcion=EString)? ","
		//"arquitectura:" arquitectura=Arquitectura ("," "rutaDestino:" rutaDestino=EString)? ("," "dependencia:" "("
		//dependencia+=[Software|EString] ("," dependencia+=[Software|EString])* ")")? ("," "origen:" "("
		//origen+=[Fuentes|EString] ("," origen+=[Fuentes|EString])* ")")? ";"
		public Group getGroup() { return cGroup; }

		//{Software}
		public Action getSoftwareAction_0() { return cSoftwareAction_0; }

		//"Software"
		public Keyword getSoftwareKeyword_1() { return cSoftwareKeyword_1; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//("," "version:" version=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//"version:"
		public Keyword getVersionKeyword_4_1() { return cVersionKeyword_4_1; }

		//version=EString
		public Assignment getVersionAssignment_4_2() { return cVersionAssignment_4_2; }

		//EString
		public RuleCall getVersionEStringParserRuleCall_4_2_0() { return cVersionEStringParserRuleCall_4_2_0; }

		//("," "descripcion:" descripcion=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//"descripcion:"
		public Keyword getDescripcionKeyword_5_1() { return cDescripcionKeyword_5_1; }

		//descripcion=EString
		public Assignment getDescripcionAssignment_5_2() { return cDescripcionAssignment_5_2; }

		//EString
		public RuleCall getDescripcionEStringParserRuleCall_5_2_0() { return cDescripcionEStringParserRuleCall_5_2_0; }

		//","
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }

		//"arquitectura:"
		public Keyword getArquitecturaKeyword_7() { return cArquitecturaKeyword_7; }

		//arquitectura=Arquitectura
		public Assignment getArquitecturaAssignment_8() { return cArquitecturaAssignment_8; }

		//Arquitectura
		public RuleCall getArquitecturaArquitecturaEnumRuleCall_8_0() { return cArquitecturaArquitecturaEnumRuleCall_8_0; }

		//("," "rutaDestino:" rutaDestino=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }

		//"rutaDestino:"
		public Keyword getRutaDestinoKeyword_9_1() { return cRutaDestinoKeyword_9_1; }

		//rutaDestino=EString
		public Assignment getRutaDestinoAssignment_9_2() { return cRutaDestinoAssignment_9_2; }

		//EString
		public RuleCall getRutaDestinoEStringParserRuleCall_9_2_0() { return cRutaDestinoEStringParserRuleCall_9_2_0; }

		//("," "dependencia:" "(" dependencia+=[Software|EString] ("," dependencia+=[Software|EString])* ")")?
		public Group getGroup_10() { return cGroup_10; }

		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }

		//"dependencia:"
		public Keyword getDependenciaKeyword_10_1() { return cDependenciaKeyword_10_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_10_2() { return cLeftParenthesisKeyword_10_2; }

		//dependencia+=[Software|EString]
		public Assignment getDependenciaAssignment_10_3() { return cDependenciaAssignment_10_3; }

		//[Software|EString]
		public CrossReference getDependenciaSoftwareCrossReference_10_3_0() { return cDependenciaSoftwareCrossReference_10_3_0; }

		//EString
		public RuleCall getDependenciaSoftwareEStringParserRuleCall_10_3_0_1() { return cDependenciaSoftwareEStringParserRuleCall_10_3_0_1; }

		//("," dependencia+=[Software|EString])*
		public Group getGroup_10_4() { return cGroup_10_4; }

		//","
		public Keyword getCommaKeyword_10_4_0() { return cCommaKeyword_10_4_0; }

		//dependencia+=[Software|EString]
		public Assignment getDependenciaAssignment_10_4_1() { return cDependenciaAssignment_10_4_1; }

		//[Software|EString]
		public CrossReference getDependenciaSoftwareCrossReference_10_4_1_0() { return cDependenciaSoftwareCrossReference_10_4_1_0; }

		//EString
		public RuleCall getDependenciaSoftwareEStringParserRuleCall_10_4_1_0_1() { return cDependenciaSoftwareEStringParserRuleCall_10_4_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_10_5() { return cRightParenthesisKeyword_10_5; }

		//("," "origen:" "(" origen+=[Fuentes|EString] ("," origen+=[Fuentes|EString])* ")")?
		public Group getGroup_11() { return cGroup_11; }

		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }

		//"origen:"
		public Keyword getOrigenKeyword_11_1() { return cOrigenKeyword_11_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_11_2() { return cLeftParenthesisKeyword_11_2; }

		//origen+=[Fuentes|EString]
		public Assignment getOrigenAssignment_11_3() { return cOrigenAssignment_11_3; }

		//[Fuentes|EString]
		public CrossReference getOrigenFuentesCrossReference_11_3_0() { return cOrigenFuentesCrossReference_11_3_0; }

		//EString
		public RuleCall getOrigenFuentesEStringParserRuleCall_11_3_0_1() { return cOrigenFuentesEStringParserRuleCall_11_3_0_1; }

		//("," origen+=[Fuentes|EString])*
		public Group getGroup_11_4() { return cGroup_11_4; }

		//","
		public Keyword getCommaKeyword_11_4_0() { return cCommaKeyword_11_4_0; }

		//origen+=[Fuentes|EString]
		public Assignment getOrigenAssignment_11_4_1() { return cOrigenAssignment_11_4_1; }

		//[Fuentes|EString]
		public CrossReference getOrigenFuentesCrossReference_11_4_1_0() { return cOrigenFuentesCrossReference_11_4_1_0; }

		//EString
		public RuleCall getOrigenFuentesEStringParserRuleCall_11_4_1_0_1() { return cOrigenFuentesEStringParserRuleCall_11_4_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_11_5() { return cRightParenthesisKeyword_11_5; }

		//";"
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }
	}
	
	
	public class ArquitecturaElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Arquitectura");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cX64EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cX64X64Keyword_0_0 = (Keyword)cX64EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cX32EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cX32X32Keyword_1_0 = (Keyword)cX32EnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Arquitectura:
		//	x64 | x32;
		public EnumRule getRule() { return rule; }

		//x64 | x32
		public Alternatives getAlternatives() { return cAlternatives; }

		//x64
		public EnumLiteralDeclaration getX64EnumLiteralDeclaration_0() { return cX64EnumLiteralDeclaration_0; }

		//"x64"
		public Keyword getX64X64Keyword_0_0() { return cX64X64Keyword_0_0; }

		//x32
		public EnumLiteralDeclaration getX32EnumLiteralDeclaration_1() { return cX32EnumLiteralDeclaration_1; }

		//"x32"
		public Keyword getX32X32Keyword_1_0() { return cX32X32Keyword_1_0; }
	}
	
	private final ConfiguracionElements pConfiguracion;
	private final SistemaOperativoElements pSistemaOperativo;
	private final EStringElements pEString;
	private final ArquitecturaElements unknownRuleArquitectura;
	private final FuentesElements pFuentes;
	private final SoftwareElements pSoftware;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pConfiguracion = new ConfiguracionElements();
		this.pSistemaOperativo = new SistemaOperativoElements();
		this.pEString = new EStringElements();
		this.unknownRuleArquitectura = new ArquitecturaElements();
		this.pFuentes = new FuentesElements();
		this.pSoftware = new SoftwareElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.mono.gesco.DSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Configuracion:
	//	{Configuracion} "Configuracion" "{" (sistemaOperativo+=SistemaOperativo ("," sistemaOperativo+=SistemaOperativo)*)?
	//	"}";
	public ConfiguracionElements getConfiguracionAccess() {
		return pConfiguracion;
	}
	
	public ParserRule getConfiguracionRule() {
		return getConfiguracionAccess().getRule();
	}

	//SistemaOperativo:
	//	{SistemaOperativo} name=EString "{" "version" version=EString "descripcion" descripcion=EString "arquitectura"
	//	arquitectura=Arquitectura ("fuentes" "{" fuentes+=Fuentes fuentes+=Fuentes* "}")? "requerimientos" "{"
	//	requerimientos+=Software requerimientos+=Software* "}" "}";
	public SistemaOperativoElements getSistemaOperativoAccess() {
		return pSistemaOperativo;
	}
	
	public ParserRule getSistemaOperativoRule() {
		return getSistemaOperativoAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//enum Arquitectura:
	//	x64 | x32;
	public ArquitecturaElements getArquitecturaAccess() {
		return unknownRuleArquitectura;
	}
	
	public EnumRule getArquitecturaRule() {
		return getArquitecturaAccess().getRule();
	}

	//Fuentes:
	//	{Fuentes} "Fuente" "=" name=EString "," "autor:" autor=EString "," "fuente:" fuente=EString "," "tipoFuente:"
	//	tipoFuente=EString ";";
	public FuentesElements getFuentesAccess() {
		return pFuentes;
	}
	
	public ParserRule getFuentesRule() {
		return getFuentesAccess().getRule();
	}

	//Software:
	//	{Software} "Software" "=" name=EString ("," "version:" version=EString)? ("," "descripcion:" descripcion=EString)?
	//	"," "arquitectura:" arquitectura=Arquitectura ("," "rutaDestino:" rutaDestino=EString)? ("," "dependencia:" "("
	//	dependencia+=[Software|EString] ("," dependencia+=[Software|EString])* ")")? ("," "origen:" "("
	//	origen+=[Fuentes|EString] ("," origen+=[Fuentes|EString])* ")")? ";";
	public SoftwareElements getSoftwareAccess() {
		return pSoftware;
	}
	
	public ParserRule getSoftwareRule() {
		return getSoftwareAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
