/**
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class DSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
