/**
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.validation;

import co.edu.uniandes.mono.gesco.validation.AbstractDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DSLValidator extends AbstractDSLValidator {
}
