/*
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DSLUiModule extends co.edu.uniandes.mono.gesco.ui.AbstractDSLUiModule {
	public DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
