/**
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.serializer;

import co.edu.uniandes.mono.gesco.serializer.AbstractDSLSemanticSequencer;

@SuppressWarnings("all")
public class DSLSemanticSequencer extends AbstractDSLSemanticSequencer {
}
