/**
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.serializer;

import co.edu.uniandes.mono.gesco.serializer.AbstractDSLSyntacticSequencer;

@SuppressWarnings("all")
public class DSLSyntacticSequencer extends AbstractDSLSyntacticSequencer {
}
