/**
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco.ui.contentassist;

import co.edu.uniandes.mono.gesco.ui.contentassist.AbstractDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
