/*
 * generated by Xtext
 */
package co.edu.uniandes.mono.gesco;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends co.edu.uniandes.mono.gesco.AbstractDSLRuntimeModule {

}
